# Generated by Django 2.0.1 on 2019-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_field',
            name='cost',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_field',
            name='Account_blnc',
            field=models.IntegerField(max_length=20),
        ),
    ]
